'''Problem
The Fibonacci numbers 0,1,1,2,3,5,8,13,21,34,… are generated by the following simple rule
Fn=⎧⎩⎨Fn−1+Fn−2,1,0,n>1,n=1,n=0.

Given: A positive integer n≤25.

Return: The value of Fn.'''

# Make a list of the first 25 Fibonacci numbers first

fibonacci = [0, 1,]

for i in range(1, 26):
    fibonacci.append(fibonacci[i] + fibonacci[i-1])

print(fibonacci)

input_num = int(input('What Fibonacci number do you want? '))
print(fibonacci[input_num])